#从文件中读取
input-file=img-gen.csv
#输出到文件夹/输出到目录
output-dir=images

#绘出的区块网格边框大小（像素）
grid-width=1
#绘出的方块大小（像素）
block-width=1

#是否绘出史莱姆区块
draw-slime-chunks=true
#是否绘出方块遮罩
draw-block-mask=true
#是否绘出区块遮罩
draw-chunk-mask=true
#是否绘出中心点
draw-center=true
