#是否覆盖现有文件
append=false
#是否进行精确搜索（显著减慢搜索速度）
fine-search=false
#输出到文件
output-file=name.csv
#中心点在区块的什么位置（默认为西北角）
center-pos=0c0,0c0
#最大搜索半径与最小搜索半径（区块为单位）
max-width=512
min-width=0
#最大有效方块数与最小有效方块数（默认）
max-block-size=73984
min-block-size=0
#最大有效区块数与最小有效区块数（默认）
max-chunk-size=289
min-chunk-size=0
